### ISSUE TITLE
Improvement: replace lazy_static with once_cell

### ISSUE THREAD

**Issue by darnuria** [Gandi/jbod-rs#19]
Hello,

I would suggest to change `lazy_static` for `once_cell`, lazy static was needed because back in 2015 in rust 1.0 it was impossible to express something like a compile time shared global ressource but safely accessed.

Since 2019, it's possible with : <https://github.com/matklad/once_cell> also the author openned a RFC PR [0000-standard-lazy-types.md](https://github.com/rust-lang/rfcs/pull/2788) to make it in std [Tracking Issue for once_cell](https://github.com/rust-lang/rust/issues/74465)

It's used here : <https://github.com/Gandi/jbod-rs/blob/main/src/prometheus.rs#L54-L71> and maybe used for regex compiled on the fly.

Gains:

- Less macro code
- API in standardisation

**Comment by araujobsd** [comment]
as it is not a critical issue, I'm closing this issue! Please, feel free to submit a PR with the proper changes.
