### ISSUE TITLE
Plannify bump of dependencies

### ISSUE THREAD

**Issue by darnuria** [Gandi/jbod-rs#20]
- [Tokio](https://github.com/tokio-rs/tokio) is in `1.22`
- [prometheus](https://github.com/tikv/rust-prometheus) is in `0.13.3`
- [futures](https://github.com/rust-lang/futures-rs) `0.3.25`
- [regex](https://github.com/rust-lang/regex) `1.7.0`
- [warp](https://github.com/seanmonstar/warp) `0.3.3` (maybe `axum` is worth considering since we use Hyper and tokio https://github.com/tokio-rs/axum)
- [prettytable-rs](https://github.com/phsym/prettytable-rs) `0.9.0`
- [hyper](https://github.com/hyperium/hyper) `0.14.23`

**Comment by araujobsd** [comment]
If possible, submit a PR with the patch.
