### ISSUE TITLE
A bit incorrect Display trait implementation

### ISSUE THREAD

**Issue by darnuria** [Gandi/jbod-rs#22]
While doing some review in `src/jbod/enclosure.rs` I found that, the implemenatation for `Display` [doc+exemple](https://doc.rust-lang.org/std/fmt/trait.Display.html)is a little bit incorrect, display expect writing to it's formatter, I suppose it could be fixed since `Table` implement `Display` : https://docs.rs/prettytable-rs/latest/prettytable/struct.Table.html#method.fmt
```rust
    /// Implementation to print the enclosure table without deal with the table.
    impl fmt::Display for Enclosure {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            let mut enclosure_table = create_enclosure_table();
            enclosure_table.add_row(Row::new(vec![
                Cell::new(&self.slot),
                Cell::new(&self.device_path),
                Cell::new(&self.vendor),
                Cell::new(&self.model),
                Cell::new(&self.revision),
                Cell::new(&self.serial),
            ]));
            
            enclosure_table.printstd(); // <- the actual issue maybe just a write! shall do the trick
            Ok(())
        }
    }
```

**Comment by araujobsd** [comment]
Feel free to submit a PR with a proper fix. For now I'm closing this ISSUE as it seems not to be critical.
